---
name: Bug Report
about: Bug issue template
title: "[BUG] <title>"
labels: ['bug']
assignees: ''

---

## 概要

発生したバグの概要を記載してください。

## 発生手順

バグを再現するための手順を記載してください。

## スクリーンショット

必要に応じてスクリーンショットをアップロードしてください。

## 発生環境

発生した環境を記載してください。ローカル環境の場合は必要に応じてOSや実行環境のバージョンも記載してください。

## 補足

必要に応じて追加情報を記載してください。
